# Generated by Django 3.1.5 on 2021-04-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否被删除')),
                ('task_name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('task_status', models.IntegerField(default=0, verbose_name='任务执行情况,0:未知错误，1:执行成功，2:执行失败')),
                ('task_result', models.JSONField(verbose_name='任务结果')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.tasklist'),
            preserve_default=False,
        ),
    ]
