# Generated by Django 3.1.5 on 2021-04-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210405_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': '任务列表', 'verbose_name_plural': '任务列表'},
        ),
        migrations.AlterModelTable(
            name='tasklist',
            table='task_list',
        ),
    ]
