# Generated by Django 3.1.5 on 2021-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210405_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_result',
            field=models.JSONField(default=dict, verbose_name='任务结果'),
        ),
    ]
