# Generated by Django 3.1.5 on 2021-02-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_websitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisit',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
