# Generated by Django 3.1.5 on 2021-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210202_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmbBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_keyword', models.TextField(blank=True, null=True)),
                ('level', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'smb_black_list',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'permissions': [('export', 'Can export user'), ('view', 'Can view user')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
