# Generated by Django 3.1.5 on 2021-03-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
